project:
  type: website
  output-dir: docs

website:
  title: "Statistics I"
  navbar:
    logo: images/iscal_logo.svg
    logo-href: https://iscal.ipl.pt
    left:
      - href: index.qmd
        text: Home
      - href: Syllabus.qmd
        text: Syllabus
      - href: Material.qmd
        text: Course Material
      - href: https://pfagandini.github.io/teaching
        text: Back to teaching

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true




